### ISSUE TITLE
想使用flask将yolov3接口化，完成剪枝量化蒸馏

### ISSUE THREAD

**Issue by Super-six-java** [chumingqian/Model_Compression_For_YOLOV3-V4#6]
作者您好
通过查看源码，发现 剪枝 量化 蒸馏 命令都需要 传递data 的路径，data 中包含的太多照片，如果每次进行一次，上传的数据太大了，不太可行（仅仅需要剪枝量化蒸馏这三个功能）
那可不可以不传递data中的图片呢 呢

**Comment by chumingqian** [comment]
你好，　剪枝，　量化，蒸馏　这三个步骤中，传入data的图片数据，　都是为了较好的观察这三个步骤，对网络模型精度的影响；
假设使用numpy, 　或者torch 随机生成网络的输入数据，　完成上述的三个步骤之后，　　网络的结构被剪枝的很小，　可是此时，　网络的精度也变得很低，　几乎不能正常预测出类别，　此时便失去了网络本身的基本检测功能了；
