### ISSUE TITLE
Fine-Tuning

### ISSUE THREAD

**Issue by tu12306** [chumingqian/Model_Compression_For_YOLOV3-V4#7]
您好， 您指出模型经过Short Cut Pruning后需要进行微调恢复模型精度，请问您指的微调操作包括哪些呢？调整网络参数还是其它的？

**Comment by chumingqian** [comment]
一般微调是指 保持参数不变， 根据任务的不同， 重新训练50～100epoch;
微调之后，  在使用知识蒸馏，提高精度。

**Comment by tu12306** [comment]
![image](https://user-images.githubusercontent.com/61649382/209521765-8a24c6b3-5fef-4a68-93f9-6de5ef1a6f2b.png)

1. 请问您文章中使用的注意力损失_LAT_是上图中哪一个呢？比如当opt.AT_str == 2时，为何要计算回归损失和分类损失呢，这个不是在损失函数Lsoft中有计算回归损失和分类损失嘛

**Comment by tu12306** [comment]
![image](https://user-images.githubusercontent.com/61649382/209522221-da87efcd-0a53-4a03-8241-e74e553b5398.png)

**Comment by tu12306** [comment]
您好，请问您文章中使用AT注意力是图片中那个函数呢？
![image](https://user-images.githubusercontent.com/61649382/209528745-12d7e15b-abce-42e9-b42c-61bb581ebe12.png)

**Comment by tu12306** [comment]
请问您文中写到蒸馏时 针对网络不同尺寸特征图进行学习，每个尺寸特征图选择哪几层是自己随便选的吗，比如Mobilenet-Yolov3有五种尺寸特征图 208 × 208, 104 × 104, 52 × 52, 26 ×26 and 13 × 13, 分为五组的话，网络中有好多层的尺寸都是52 x 52 也就是下采样8倍请问这个时候选择哪几层进行蒸馏呢

**Comment by chumingqian** [comment]
您好，进行蒸馏的过程中，　在分组的过程中我们将相同尺寸的特征图分成一组，　在蒸馏过程中便是将每组中最后一个特征图拿出来进行学习。

**Comment by tu12306** [comment]
这个蒸馏分组跟您的剪枝分组不一样是嘛？也就是说将要蒸馏的特征图分为下采样2倍、下采样4倍、下采样8倍、下采样16倍、下采样32倍五组，前三组系数是1000，后两组系数是10000。这里下采样特征图的倍数是针对原始图片尺寸而言的。您的剪枝分组更多是针对网络特征提取和特征融合分成五组，这样理解对吧？发自我的荣耀手机-------- 原始邮件 --------发件人： chumingqian ***@***.***>日期： 2023年2月24日周五 上午10:52收件人： chumingqian/Model_Compression_For_YOLOV3-V4 ***@***.***>抄送： tttu ***@***.***>, State change ***@***.***>主    题： Re: [chumingqian/Model_Compression_For_YOLOV3-V4] Fine-Tuning (Issue #7)

您好，进行蒸馏的过程中，　在分组的过程中我们将相同尺寸的特征图分成一组，　在蒸馏过程中便是将每组中最后一个特征图拿出来进行学习。
