### ISSUE TITLE
KD loss

### ISSUE THREAD

**Issue by tu12306** [chumingqian/Model_Compression_For_YOLOV3-V4#8]
您好， 请问您进行分组注意力蒸馏时每组选取层数的依据是什么呀？看到您的多个注意力蒸馏损失函数中选取的层数还不一样

**Comment by chumingqian** [comment]
你好， 分组 当时主要考虑了两个方面的内容：
 1.   具有相同的网络结构的模块划分到同一组中， 具有shutcut 连接的尽量安排在同一组中；
 2.     实验中，发现不同层的重要性不等， 比方说，网络最初的几个层，重要性就比较大， 此时，该组中剪枝率就不能设置太高；  而到最后的几个网络层，此时重要性降低， 此时，改组的剪枝率就可以设置较大。
